services:
  postgres_db:
    image: postgres
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    ports:
      - "5435:5432"
  pgadmin:
    container_name: pgadmin-prod
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
  gateway:
    container_name: gateway
    image: mta2003/gateway:gb
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres_db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - MAIN_BACKEND_HOST=main_backend
      - COMMENT_BACKEND_HOST=comment_backend
  main_backend:
    container_name: main_backend
    image: mta2003/main_backend:mb
    ports:
      - "50050:50050"
      - "50051:50051"
    env_file:
      - .env
    depends_on:
      - postgres_db
      - gateway
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - MAIN_BACKEND_HOST=main_backend
  comment_backend:
    container_name: comment_backend
    image: mta2003/comment_backend:cb
    ports:
      - "50052:50052"
    env_file:
      - .env
    depends_on:
      - postgres_db
      - gateway
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - COMMENT_BACKEND_HOST=comment_backend
