services:
  postgres_maindb:
    image: postgres
    container_name: test_e2e
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    ports:
      - '5435:5432'
  main_backend:
    container_name: main_backend_to_test
    build:
      context: ../
      dockerfile: MainAppDockerfile
    ports:
      - '50050:50050'
      - '50051:50051'
    env_file:
      - ../.env
    depends_on:
      - postgres_maindb
    environment:
      - POSTGRES_HOST=test_e2e
      - POSTGRES_PORT=5432
      - MAIN_BACKEND_HOST=main_backend
  comment_backend:
    container_name: comment_backend_to_test
    build:
      context: ../
      dockerfile: CommentServiceDockerfile
    ports:
      - '50052:50052'
    env_file:
      - ../.env
    depends_on:
      - postgres_maindb
      - main_backend
    environment:
      - POSTGRES_HOST=test_e2e
      - POSTGRES_PORT=5432
      - COMMENT_BACKEND_HOST=comment_backend
